[package]
name = "AI_project"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.3.1"
linfa = "0.7.1"
linfa-clustering = "0.7.1"
linfa-nn = "0.7.1"
linfa-trees = "0.7.1"
ndarray = "0.16.1"
ndarray-csv = "0.5.3"
